[project]
name = "crf_endereco"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.4.1",
    "markitdown[docx,pdf,xls,xlsx]>=0.1.8",
    "matplotlib>=3.10.7",
    "python-dotenv>=1.2.4",
    "rapidfuzz>=3.14.6",
    "requests>=2.34.2",
    "rich>=15.0.0",
    "scikit-learn>=1.7.2",
    "sklearn-crfsuite>=0.5.0",
    "typer>=0.27.2",
]

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.uv]
package = true

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
]
